@startuml
'https://plantuml.com/sequence-diagram

autonumber
boundary " User"
actor Player
'actor Creature #red
Player -> Lake: Move player around

activate Lake
Mods -> Lake: Move Mods to the room
group Play Game until User Finished Playing
Lake -> "Check the surrounding": is there any Mods close by?
"Check the surrounding" --> Lake: Yes
Lake -> Fight: Fight the Mod

Fight -> "Check Mode Type": Is The Player weapon Stronger than Creature Weapon?
"Check Mode Type" --> Fight: Yes
Fight -> Defeated: Mod Defeated
activate Defeated
Defeated --> Lake: Remove Mod from the room
destroy Defeated
"Check Mode Type" --> Fight: No
Fight -> Lake:  the Player got damage points or Avoid the Attack and collect \n dragon teeth, piranha scales to Creat weapons
"Check the surrounding" --> Lake: Yes

Lake -> "Search for a Mobs/Loots": Search For Treasure/Loots to Collect
"Search for a Mobs/Loots" -> Treasure: Any Treasure Available
Treasure --> "Search for a Mobs/Loots": Yes
"Search for a Mobs/Loots" -> Player: Collect Treasure



end
deactivate Lake
destroy Lake

Lake ->" User": Done
@enduml