
@startuml
'https://plantuml.com/activity-diagram-beta

start
:Start game;
:Creat Mobs;
:Check the surrounding;



repeat
:Move player around;
':Move Creatures to room;
  if ( Lava Lake) is (No) then
    :Be careful and far from lava;

  else (Yes)
  :Search for a Mobs/Loots to next;
  if (Player find treasure) is (No) then
    :keep walking and searching;
  else (yes)
    :The Player Collect it and gain Items;
    if (Is the Player too Close to Hidden Mob) is (yes) then
    if (Hidden Mob?) is (Lava dragon) then
      :Lava dragon;
      if (position?) is (Flying) then
        :true;
        if (Is the player near?) is (yes) then
          :Shoot Lava;
          if (Hit the Player hits ?) is (yes) then
            :Player git Damage;
          else (no)
            :Continue;
          endif
        else (no)
          :false;
        endif
      else (Sleeping)
        :false;
      endif

'      :Lava dragon weaken;
      if (Player has Dragon Sward?) is (yes) then
        if (Player hits the Dragon?) is (yes) then
          :Lava dragon defeated;
          :Collect the Spoils;
        else (no)
          :false;
        endif



      else (no)
        if (Hit the Player Hits the dragon with weapon?) is (yes) then
          :Dragon take Damage;
        else (no)
          :False;
        endif

      endif
    else (lava piranha)
      :The lava piranha;
      if (jump out of the lava to attack the player?) is (yes) then
        :Fight;
        if (Player killed the piranha?) is (yes) then
          :Collect Piranha Scales;
          if (Player 4 OR More Prianha scales?) is (yes) then
            :Creat Lava Boots;
          else (no)
            :Continue Searching;
          endif
        else (no)
          :Player Take Damage;
        endif
      else (no)
        :Continue;
      endif
    endif
      :Continue walking;
    else (no)
     :Continue;
    endif


if (The Player Find way out) then (No)

  else (Yes)
  :Player Won;
  stop


@enduml
