@startuml
'https://plantuml.com/sequence-diagram

autonumber
boundary " User"
actor Player
'actor Creature #red
Player -> Lake: Move player around

activate Lake
Modes -> Lake: Move Creature to the room
group Play Game until End conditions is True
Lake -> "Check the surrounding": is there any Modes close by?
"Check the surrounding" --> Lake: Yes
Lake -> Fight: Fight the Creature

Fight -> "Check Mode Type": Is The Player weapon Stronger than Creature Weapon?
"Check Mode Type" --> Fight: Yes
Fight -> Defeated: Creature Defeated
activate Defeated
Defeated --> Lake: Remove Creature from the room
destroy Defeated
"Check Mode Type" --> Fight: No
Fight -> Lake:  the Player got damage points or Avoid the Attack and collect \n dragon teeth, piranha scales to Creat weapons
"Empty Room" --> Lake: Yes

Lake -> Search: Search For Treasure
Search -> Treasure: Any Treasure Avalibale
Treasure --> Search: Yes
Search -> Adventurer: Collect Treasure



end
deactivate Room
destroy Room

Room ->" User": Done
@enduml